/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.rendering.PDFRenderer;
/**
 *
 * @author Basudewa
 */
public class Student extends javax.swing.JFrame {

    private DefaultTableModel materiModel;
    private DefaultTableModel bookmarkModel;
    
    private FileInputStream fis;
    private File selectedFile;
    
    Login login = new Login();
    /**
     * Creates new form Lecturer
     */
    public Student() {
        initComponents();
        
        materiModel = new DefaultTableModel();
        MateriTable.setModel(materiModel);
        materiModel.addColumn("Id Materi");
        materiModel.addColumn("Nama Materi");
        
       loadMateriData();
       
       bookmarkModel = new DefaultTableModel();
        BookmarkTable.setModel(bookmarkModel);
        bookmarkModel.addColumn("Id Materi");
        bookmarkModel.addColumn("Nama Materi");
        
        loadBookmarkData();
       
        usernameLabel.setText(login.currentUser.getUsername());
        jButton1.setVisible(false);
    }
    
    private void loadMateriData() {
        materiModel.getDataVector().removeAllElements();
        materiModel.fireTableDataChanged();
        
        try {
            Connection connection = DatabaseConnection.getConnection();
            String query = "SELECT * FROM materi";
            // TODO : query semua materi 
            PreparedStatement statement = connection.prepareStatement(query);
            
            ResultSet resultSet = statement.executeQuery();
            
            while(resultSet.next()) {
                Object[] o = new Object[3];
                o[0] = resultSet.getString("id_materi");
                o[1] = resultSet.getString("judul_materi");
                
                materiModel.addRow(o);
            }
            
            resultSet.close();            
            statement.close();
            connection.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
    }
    
    private void loadBookmarkData() {
     bookmarkModel.getDataVector().removeAllElements();
     bookmarkModel.fireTableDataChanged();
        
        try {
            Connection connection = DatabaseConnection.getConnection();
            String query = "SELECT bookmark.id_materi, materi.judul_materi FROM bookmark JOIN materi ON bookmark.id_materi = materi.id_materi WHERE id_user = ? ";
            // TODO : query bookmark user ini saja
            PreparedStatement statement = connection.prepareStatement(query);
            
            statement.setInt(1, login.currentUser.getId());
            
            ResultSet resultSet = statement.executeQuery();
            
            while(resultSet.next()) {
                Object[] o = new Object[3];
                o[0] = resultSet.getString("id_materi");
                o[1] = resultSet.getString("judul_materi");
                
                bookmarkModel.addRow(o);
            }
            
            resultSet.close();            
            statement.close();
            connection.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
    }
 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        TabPane = new javax.swing.JTabbedPane();
        AddMateriPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MateriTable = new javax.swing.JTable();
        materiSayaLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pdfScrollPane = new javax.swing.JScrollPane();
        pdfPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        AddDiskusiPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookmarkTable = new javax.swing.JTable();
        DiskusiLabel = new javax.swing.JLabel();
        pdfScrollPane1 = new javax.swing.JScrollPane();
        pdfPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BookmarkNavigator = new javax.swing.JButton();
        MateriNavigator = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1442, 870));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1450, 70));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DISTUDY");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/Rectangle 77.png"))); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 861, Short.MAX_VALUE)
                .addComponent(usernameLabel)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(usernameLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, -1));

        TabPane.setBackground(new java.awt.Color(255, 255, 255));

        AddMateriPanel.setBackground(new java.awt.Color(255, 255, 255));

        MateriTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MateriTable.setForeground(new java.awt.Color(51, 153, 255));
        MateriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MateriTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MateriTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MateriTable);

        materiSayaLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        materiSayaLabel.setForeground(new java.awt.Color(51, 153, 255));
        materiSayaLabel.setText("Materi Saya");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Rectangle 79.png"))); // NOI18N
        jLabel4.setText("BG");

        javax.swing.GroupLayout pdfPanelLayout = new javax.swing.GroupLayout(pdfPanel);
        pdfPanel.setLayout(pdfPanelLayout);
        pdfPanelLayout.setHorizontalGroup(
            pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        pdfPanelLayout.setVerticalGroup(
            pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        pdfScrollPane.setViewportView(pdfPanel);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bookmark");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddMateriPanelLayout = new javax.swing.GroupLayout(AddMateriPanel);
        AddMateriPanel.setLayout(AddMateriPanelLayout);
        AddMateriPanelLayout.setHorizontalGroup(
            AddMateriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMateriPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(AddMateriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materiSayaLabel)
                    .addGroup(AddMateriPanelLayout.createSequentialGroup()
                        .addGroup(AddMateriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddMateriPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pdfScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        AddMateriPanelLayout.setVerticalGroup(
            AddMateriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMateriPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(materiSayaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddMateriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMateriPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40))
                    .addGroup(AddMateriPanelLayout.createSequentialGroup()
                        .addGroup(AddMateriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pdfScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        TabPane.addTab("tab1", AddMateriPanel);

        AddDiskusiPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddDiskusiPanel.setLayout(null);

        BookmarkTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BookmarkTable.setForeground(new java.awt.Color(51, 153, 255));
        BookmarkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookmarkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookmarkTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(BookmarkTable);

        AddDiskusiPanel.add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 350, 402);

        DiskusiLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        DiskusiLabel.setForeground(new java.awt.Color(51, 153, 255));
        DiskusiLabel.setText("Bookmark Saya");
        AddDiskusiPanel.add(DiskusiLabel);
        DiskusiLabel.setBounds(20, 30, 169, 29);

        javax.swing.GroupLayout pdfPanel1Layout = new javax.swing.GroupLayout(pdfPanel1);
        pdfPanel1.setLayout(pdfPanel1Layout);
        pdfPanel1Layout.setHorizontalGroup(
            pdfPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        pdfPanel1Layout.setVerticalGroup(
            pdfPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        pdfScrollPane1.setViewportView(pdfPanel1);

        AddDiskusiPanel.add(pdfScrollPane1);
        pdfScrollPane1.setBounds(380, 70, 851, 732);

        TabPane.addTab("tab1", AddDiskusiPanel);

        getContentPane().add(TabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 840));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        BookmarkNavigator.setBackground(new java.awt.Color(0, 0, 51));
        BookmarkNavigator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookmarkNavigator.setForeground(new java.awt.Color(255, 255, 255));
        BookmarkNavigator.setText("Bookmarks");
        BookmarkNavigator.setBorder(null);
        BookmarkNavigator.setBorderPainted(false);
        BookmarkNavigator.setContentAreaFilled(false);
        BookmarkNavigator.setFocusPainted(false);
        BookmarkNavigator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookmarkNavigatorActionPerformed(evt);
            }
        });

        MateriNavigator.setBackground(new java.awt.Color(51, 153, 255));
        MateriNavigator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MateriNavigator.setForeground(new java.awt.Color(255, 255, 255));
        MateriNavigator.setText("Materi");
        MateriNavigator.setBorder(null);
        MateriNavigator.setBorderPainted(false);
        MateriNavigator.setFocusPainted(false);
        MateriNavigator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriNavigatorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MateriNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BookmarkNavigator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MateriNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookmarkNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(675, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MateriTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriTableMouseClicked
        int i = MateriTable.getSelectedRow();
        TableModel model = MateriTable.getModel();
        
        jButton1.setVisible(true);
        try {
            Connection connection = DatabaseConnection.getConnection();
            String query = "SELECT * FROM materi WHERE id_materi = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            
            statement.setInt(1, Integer.parseInt(model.getValueAt(i, 0).toString()));

            
            ResultSet resultSet = statement.executeQuery();
            

            if (resultSet.next()) {
                Blob blob = resultSet.getBlob("data_materi");
                InputStream inputStream = blob.getBinaryStream();

                PDDocument document = PDDocument.load(inputStream);
                PDFRenderer pdfRenderer = new PDFRenderer(document);

                int numPages = document.getNumberOfPages();
                pdfPanel.removeAll();
                pdfPanel.setLayout(new GridLayout(numPages, 1));

                for (int j = 0; j < numPages; j++) {
                    BufferedImage image = pdfRenderer.renderImageWithDPI(j, 100);
                    JLabel label = new JLabel(new ImageIcon(image));
                    pdfPanel.add(label);
                }

                pdfScrollPane.revalidate();
                pdfScrollPane.repaint();
            } else {
            }
        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_MateriTableMouseClicked

    private void BookmarkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookmarkTableMouseClicked
      int i = BookmarkTable.getSelectedRow();
        TableModel model = BookmarkTable.getModel();
        
        try {
            Connection connection = DatabaseConnection.getConnection();
            String query = "SELECT * FROM materi WHERE id_materi = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            
            statement.setInt(1, Integer.parseInt(model.getValueAt(i, 0).toString()));

            
            ResultSet resultSet = statement.executeQuery();
            

            if (resultSet.next()) {
                Blob blob = resultSet.getBlob("data_materi");
                InputStream inputStream = blob.getBinaryStream();

                PDDocument document = PDDocument.load(inputStream);
                PDFRenderer pdfRenderer = new PDFRenderer(document);

                int numPages = document.getNumberOfPages();
                pdfPanel1.removeAll();
                pdfPanel1.setLayout(new GridLayout(numPages, 1));

                for (int j = 0; j < numPages; j++) {
                    BufferedImage image = pdfRenderer.renderImageWithDPI(j, 100);
                    JLabel label = new JLabel(new ImageIcon(image));
                    pdfPanel1.add(label);
                }

                pdfScrollPane1.revalidate();
                pdfScrollPane1.repaint();
            } else {
            }
        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_BookmarkTableMouseClicked

    private void MateriNavigatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriNavigatorActionPerformed
        TabPane.setSelectedIndex(0);
        
        BookmarkNavigator.setContentAreaFilled(false);
        BookmarkNavigator.setBackground(new Color(0, 0, 51));
        
        MateriNavigator.setContentAreaFilled(true);
        MateriNavigator.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_MateriNavigatorActionPerformed

    private void BookmarkNavigatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookmarkNavigatorActionPerformed
        TabPane.setSelectedIndex(1);
        
        BookmarkNavigator.setContentAreaFilled(true);
        BookmarkNavigator.setBackground(new Color(51, 153, 255));
        
        MateriNavigator.setContentAreaFilled(false);
        MateriNavigator.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_BookmarkNavigatorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = MateriTable.getSelectedRow();
        TableModel model = MateriTable.getModel();
        try {
            Connection connection = DatabaseConnection.getConnection();
            String query = "INSERT INTO bookmark(id_user, id_materi) VALUES (?,?)";
            PreparedStatement statement = connection.prepareStatement(query);

            statement.setInt(1, login.currentUser.getId());
            statement.setInt(2, Integer.parseInt(model.getValueAt(i, 0).toString()));

            statement.execute();
            
            statement.close();
            connection.close();
}
catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDiskusiPanel;
    private javax.swing.JPanel AddMateriPanel;
    private javax.swing.JButton BookmarkNavigator;
    private javax.swing.JTable BookmarkTable;
    private javax.swing.JLabel DiskusiLabel;
    private javax.swing.JButton MateriNavigator;
    private javax.swing.JTable MateriTable;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel materiSayaLabel;
    private javax.swing.JPanel pdfPanel;
    private javax.swing.JPanel pdfPanel1;
    private javax.swing.JScrollPane pdfScrollPane;
    private javax.swing.JScrollPane pdfScrollPane1;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
